name: Build and Test

on:
  push:
    paths:
      - 'simpleppt/**'

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install coverage pytest
        pip install .
    - name: Test with pytest
      run: |
        coverage run -m pytest simpleppt/tests/test_all.py
        coverage report -m
        coverage xml
    - name: Upload coverage to Codecov
      if: ${{ matrix.python-version == '3.8' }}
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}

  pypi_upload:
    if: |
      contains(github.event.head_commit.message, 'pypi test') ||
      startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
      - name: Build wheel
        run: |
          python setup.py bdist_wheel
          python setup.py sdist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
        if: startsWith(github.ref, 'refs/tags/v')
